const PRODUCT_LIST = 'PRODUCT_LIST';
const PRODUCT_CREATE = 'PRODUCT_CREATE'
const PRODUCT_DETAILS = 'PRODUCT_DETAILS'
const PRODUCT_DELETE = 'PRODUCT_DELETE'

const types = {
    PRODUCT_LIST,
    PRODUCT_DETAILS,
    PRODUCT_CREATE,
	PRODUCT_DELETE
};

export default types;