const MOVIE_LIST = 'MOVIE_LIST';
const MOVIE_ADD = 'MOVIE_ADD';
const MOVIE_DELETE = 'MOVIE_DELETE'
const MOVIE_EDIT = 'MOVIE_EDIT'
const MOVIE_EDIT_DIRECTOR = 'MOVIE_EDIT_DIRECTOR'

const types = {
    MOVIE_LIST,
	MOVIE_ADD,
	MOVIE_DELETE,
	MOVIE_EDIT,
	MOVIE_EDIT_DIRECTOR
};


export default types;