const PERSON_LIST = 'PERSON_LIST';
const PERSON_ADD = 'PERSON_ADD';
const PERSON_DELETE = 'PERSON_DELETE'
const PERSON_EDIT = 'PERSON_EDIT'

const types = {
    PERSON_LIST,
	PERSON_ADD,
	PERSON_DELETE,
	PERSON_EDIT
};


export default types;