const PERSON_LIST_REQUEST = 'PERSON_LIST_REQUEST';
const PERSON_LIST_SUCCESS = 'PERSON_LIST_SUCCESS';
const PERSON_LIST_FAILURE = 'PERSON_LIST_FAILURE';

const PERSON_ADD_REQUEST = 'PERSON_ADD_REQUEST';
const PERSON_ADD_SUCCESS = 'PERSON_ADD_SUCCESS';
const PERSON_ADD_FAILURE = 'PERSON_ADD_FAILURE';

const PERSON_DELETE = 'PERSON_DELETE'

const PERSON_EDIT_REQUEST = 'PERSON_EDIT_REQUEST';
const PERSON_EDIT_SUCCESS = 'PERSON_EDIT_SUCCESS';
const PERSON_EDIT_FAILURE = 'PERSON_EDIT_FAILURE';

const types = {
	PERSON_LIST_REQUEST,
    PERSON_LIST_SUCCESS,
	PERSON_LIST_FAILURE,
	PERSON_ADD_REQUEST,
	PERSON_ADD_SUCCESS,
	PERSON_ADD_FAILURE,
	PERSON_DELETE,
	PERSON_EDIT_REQUEST,
	PERSON_EDIT_SUCCESS,
	PERSON_EDIT_FAILURE
};


export default types;