const ACTOR_LIST_REQUEST = 'ACTOR_LIST_REQUEST';
const ACTOR_LIST_SUCCESS = 'ACTOR_LIST_SUCCESS';
const ACTOR_LIST_FAILURE = 'ACTOR_LIST_FAILURE';


const ACTOR_ADD_REQUEST = 'ACTOR_ADD_REQUEST';
const ACTOR_ADD_SUCCESS = 'ACTOR_ADD_SUCCESS';
const ACTOR_ADD_FAILURE = 'ACTOR_ADD_FAILURE';

const ACTOR_DELETE_REQUEST = 'ACTOR_DELETE_REQUEST';
const ACTOR_DELETE_SUCCESS = 'ACTOR_DELETE_SUCCESS';
const ACTOR_DELETE_FAILURE = 'ACTOR_DELETE_FAILURE';
const ACTOR_DELETE = 'ACTOR_DELETE'

//const ACTOR_IN_MOVIE_REQUEST = 'ACTOR_IN_MOVIE_REQUEST';
//const ACTOR_IN_MOVIE_SUCCESS = 'ACTOR_IN_MOVIE_SUCCESS';
//const ACTOR_IN_MOVIE_FAILURE = 'ACTOR_IN_MOVIE_FAILURE';


const types = {
	ACTOR_LIST_REQUEST,
    ACTOR_LIST_SUCCESS,
	ACTOR_LIST_FAILURE,
	ACTOR_ADD_REQUEST,
	ACTOR_ADD_SUCCESS,
	ACTOR_ADD_FAILURE,
	ACTOR_DELETE_REQUEST,
	ACTOR_DELETE_SUCCESS,
	ACTOR_DELETE_FAILURE,
	ACTOR_DELETE,
	//ACTOR_IN_MOVIE_REQUEST,
	//ACTOR_IN_MOVIE_SUCCESS,
	//ACTOR_IN_MOVIE_FAILURE
};


export default types;