const USER_CREATE = 'USER_CREATE'
const USER_DETAILS = 'USER_DETAILS'

const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
const USER_LIST_FAILURE = 'USER_LIST_FAILURE';

const types = {
    USER_DETAILS,
    USER_CREATE,
    USER_LIST_REQUEST,
    USER_LIST_FAILURE,
    USER_LIST_SUCCESS
};

export default types;